name: Continuous Integration

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16
          - 17

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules/
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('package*.json') }}
      - run: npm install
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm test
      - run: npm run lint
