name: Continuous Integration

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run ESlint
        run: npm run lint
