name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run : npm ci --ignore-scripts
      - name: Publish to npm
        run : |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm run publish:npm
        env :
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
